### PR TITLE
finished file parser with tests

### PR DESCRIPTION
**Pull request by Verkhovskaya**

### CODE REVIEW

**Comment by anderscognite** [comment]
Since the tests aren't passing (my fault), we should wait with this PR until that is fixed. I hope to do that today, and I'll merge my branch into yours, to then merge that back into mine again :D 

Nice work!

**Comment by anderscognite** [comment]
Are the tests passing?

**Comment by Verkhovskaya** [comment]
Tests are passing:

----------------------------|----------|----------|----------|----------|-------------------|
File                        |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------------------------|----------|----------|----------|----------|-------------------|
All files                   |    83.01 |    66.59 |    84.51 |    83.07 |                   |
 src                        |    91.23 |    85.71 |    85.71 |    92.35 |                   |
  Parser.ts                 |    94.87 |       75 |      100 |    94.74 |             67,68 |
  PathExtractor.ts          |      100 |      100 |      100 |      100 |                   |
  ProtobufDecoder.ts        |    79.17 |        0 |       80 |    78.26 |    23,24,27,28,46 |
  Sector.ts                 |    60.98 |        0 |    57.14 |    66.67 |... 53,56,57,58,62 |
  TestUtils.ts              |      100 |      100 |      100 |      100 |                   |
  constants.ts              |      100 |      100 |      100 |      100 |                   |
  customParser.ts           |    96.43 |    97.73 |    92.86 |    96.35 |... 3,94,96,97,158 |
 src/geometry               |    79.01 |    57.14 |    83.87 |    78.74 |                   |
  BaseCylinderGroup.ts      |       95 |       50 |     87.5 |    94.74 |                38 |
  BoxGroup.ts               |      100 |       50 |      100 |      100 |                20 |
  CircleGroup.ts            |      100 |       50 |      100 |      100 |                38 |
  ConeGroup.ts              |    83.78 |    83.33 |    84.62 |    83.56 |... 56,157,158,160 |
  EccentricConeGroup.ts     |    77.78 |       50 |    81.82 |    77.36 |... 89,92,93,94,96 |
  EllipsoidSegmentGroup.ts  |    60.22 |       50 |       50 |    59.78 |... 83,185,196,200 |
  GeneralCylinderGroup.ts   |     97.3 |       50 |     91.3 |    97.26 |           142,146 |
  GeneralRingGroup.ts       |    89.19 |    83.33 |    88.24 |    89.04 |... 41,142,143,151 |
  GeometryGroup.ts          |       40 |        0 |       50 |    44.44 |    13,14,16,18,21 |
  NutGroup.ts               |    64.41 |       50 |    77.78 |    63.79 |... 92,93,94,95,98 |
  PlaneGroup.ts             |      100 |       50 |      100 |      100 |                10 |
  PrimitiveGroup.ts         |    67.61 |    66.67 |    90.91 |    67.14 |... 60,166,172,178 |
  QuadGroup.ts              |    63.77 |       50 |       75 |    63.24 |... 23,124,125,128 |
  SphericalSegmentGroup.ts  |    77.14 |       25 |    78.57 |    76.81 |... 59,160,161,170 |
  TorusSegmentGroup.ts      |    72.97 |       50 |    84.62 |     72.6 |... 36,141,145,155 |
  TrapeziumGroup.ts         |    86.54 |       50 |    84.62 |    86.27 |... 08,109,110,111 |
 src/parsers                |    84.38 |    65.01 |    85.71 |    84.66 |                   |
  parseBoxes.ts             |      100 |    77.27 |      100 |      100 |          41,44,47 |
  parseCircles.ts           |    98.82 |    78.13 |      100 |    98.61 |                91 |
  parseCones.ts             |    93.65 |    71.05 |      100 |    92.59 |       33,78,79,80 |
  parseEccentricCones.ts    |      100 |       65 |      100 |      100 |          42,45,50 |
  parseEllipsoidSegments.ts |      100 |    88.89 |      100 |      100 |             39,42 |
  parseGeneralCylinders.ts  |    53.85 |        0 |    33.33 |    53.85 | 14,19,20,21,22,26 |
  parseGeneralRings.ts      |    78.02 |    62.69 |     87.5 |    79.49 |... ,96,99,100,171 |
  parseNuts.ts              |      100 |    55.56 |      100 |      100 |          39,42,44 |
  parseQuads.ts             |    43.14 |    15.79 |       60 |    46.81 |... 74,77,82,84,86 |
  parseSphericalSegments.ts |      100 |    88.89 |      100 |      100 |             39,46 |
  parseTorusSegments.ts     |      100 |       85 |      100 |      100 |          40,43,50 |
  parseTrapeziums.ts        |    54.41 |    31.43 |    55.56 |    56.67 |... 0,81,82,90,113 |
  parseUtils.ts             |    91.67 |       50 |      100 |    91.67 |                11 |
----------------------------|----------|----------|----------|----------|-------------------|

Test Suites: 33 passed, 33 total
Tests:       105 passed, 105 total
Snapshots:   0 total
Time:        4.886s
Ran all test suites.

**Comment by anderscognite** [comment]
Nice! What about linting? If you haven't enabled automatic lint on save, there is probably quite a few linting errors. Run `yarn lint` to see (and enable it in VSCode). If linting is ok, I'll review :D

**Comment by Verkhovskaya** [comment]
Fixed linting

**Comment by anderscognite** [comment]
https://github.com/cognitedata/3d-web-parser/pull/3 instead

**Pull request closed without merging**
