### PR TITLE
Added copyright headers and removed protobuf tests

### PR DESCRIPTION
**Pull request by anderscognite**
Protobuf tests weren't implemented and as we are dropping protobuf support, we might as well just remove them.

### CODE REVIEW

**Review by Verkhovskaya — COMMENTED** [review]
LGTM. Although, do you remove the src/__tests__/protobufParser folder anywhere?

**Comment by anderscognite** [comment]
I don't think git contains empty folders, so I think it's gone :)

**Comment by Verkhovskaya** [comment]
Cool, TIL

**Comment by anderscognite** [comment]
If that's what you want (empty folders), you have to use tricks: https://stackoverflow.com/questions/115983/how-can-i-add-an-empty-directory-to-a-git-repository

**Review by Verkhovskaya — APPROVED** [review]

**Pull request merged**
