### PR TITLE
Added more statistics and some cleanup

### PR DESCRIPTION
**Pull request by anderscognite**

### CODE REVIEW

**Review by Verkhovskaya — APPROVED** [review]
LGTM, although one question. If .type is a public property on PrimitiveGroup, why do you also need to add it to all of the child classes? Is it because it's abstract?

**Review by nsunderland-cognite — APPROVED** [review]
Looks good.

**Comment by nsunderland-cognite** [comment]
> LGTM, although one question. If .type is a public property on PrimitiveGroup, why do you also need to add it to all of the child classes? Is it because it's abstract?

Basically, yeah. And if it isn't abstract, TS will complain about it not being initialized.

**Comment by Verkhovskaya** [comment]
Cool cool

**Comment by Verkhovskaya** [comment]
You could also initialise it to ‘Primitive’, though, if you wanted

**Pull request merged**
